#ifndef _SDPI_IP_CONFIG_H
#define _SDPI_IP_CONFIG_H
#include "sdpi_flow_parser.h"

typedef struct _sdpi_ip_config
{
	char					*ip_addr;
	unsigned int 			mask_bits;
	sdpi_inspect_result_t	result;
}sdpi_ip_config_t;

static sdpi_inspect_result_t
sdpi_unknown_ip_result = \
	{SDPI_INSPECTED_BY_IP, SDPI_APP_UNKNOWN, SDPI_APP_CATEGORY_UNKNOWN, "ip unknown"};

static const sdpi_ip_config_t
sdpi_ip_config_list[] =
{
	//youku:主IP浮动频率太高，不考虑根据IP匹配

	//bilibili: www.bilibili, s1.hdslb, data.bilibili, i0.hdslb, i1.hdslb, i2.hdslb, static.hdslb, api.bilibili
	//api.live.bilibili, cm.bilibili
	{ "111.230.84.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_BILIBILI, SDPI_APP_CATEGORY_VIDEO, "bilibili video" } },
	{ "124.227.25.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_BILIBILI, SDPI_APP_CATEGORY_VIDEO, "bilibili video" } },
	{ "171.107.80.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_BILIBILI, SDPI_APP_CATEGORY_VIDEO, "bilibili video" } },
	{ "14.29.39.0",      24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_BILIBILI, SDPI_APP_CATEGORY_VIDEO, "bilibili video" } },
	{ "106.75.162.231",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_BILIBILI, SDPI_APP_CATEGORY_VIDEO, "bilibili video" } },
	{ "111.230.85.89",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_BILIBILI, SDPI_APP_CATEGORY_VIDEO, "bilibili video" } },
	{ "106.75.152.221",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_BILIBILI, SDPI_APP_CATEGORY_VIDEO, "bilibili video" } },
	{ "106.75.164.19",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_BILIBILI, SDPI_APP_CATEGORY_VIDEO, "bilibili live" } },

	//iqiyi视频: www.iqiyi, stc.iqiyipic, security.iqiyi, pic?.iqiyipic, www.iqiyipic, t7z.cupid.iqiyi
	//a.irs01, cache.video.iqiyi, iqiyi.irs01, act.vip.iqiyi, pcw-api.iqiyi, nl-notice.iqiyi,
	////data.video.iqiyi, control-i.iqiyi, api.vip.iqiyi, serv.vip.iqiyi
	{ "121.12.108.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "59.38.101.0",     24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "183.61.178.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "101.227.32.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "116.211.186.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "106.38.219.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "101.227.200.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "180.153.123.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "116.211.189.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "106.38.178.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "115.182.224.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "36.110.134.200",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "36.110.224.50",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },
	{ "101.227.32.59",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_IQIYI, SDPI_APP_CATEGORY_VIDEO, "iqiyi video" } },

	//tencent视频: v.qq, js.aq.qq, video.qq, node.video.qq, btrace.video.qq, tj.video, pay.video.qq, 
	//access.video.qq, bullet.video.qq, mfm.video.qq, p.l.qq, routertips.video.qq,
	//dp3.qq, vd.l.qq, like.video.qq, video.coral.qq, ugcbsy.qq, ncgi.video.qq, ltsws.qq
	{ "222.218.81.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "119.147.83.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "14.17.52.0",      24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "14.17.41.183",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "183.3.226.0",     24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "183.36.108.190",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "183.57.48.67",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "59.37.96.188",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "183.3.234.245",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "219.133.60.236",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "183.61.51.0",     24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "183.232.91.21",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "183.3.235.211",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "14.119.126.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "113.96.75.0",     24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "113.16.215.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "183.3.235.150",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "113.16.212.106",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "113.16.210.80",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "125.77.133.3",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "59.56.28.2",      32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },
	{ "27.155.108.252",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_TENCENT, SDPI_APP_CATEGORY_VIDEO, "tencent video" } },

	////搜狐视频：tv.sohu, pv.sohu,rc.vrs.sohu, api.my.tv.sohu（主要是包含资源）
	{ "14.18.240.0",  	 24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_SOHU, SDPI_APP_CATEGORY_VIDEO, "sohu video" } },
	{ "113.96.179.243",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_SOHU, SDPI_APP_CATEGORY_VIDEO, "sohu video" } },
	{ "121.11.0.225",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_SOHU, SDPI_APP_CATEGORY_VIDEO, "sohu video" } },
	{ "222.218.87.132",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_SOHU, SDPI_APP_CATEGORY_VIDEO, "sohu video" } },
	{ "220.181.11.55",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_SOHU, SDPI_APP_CATEGORY_VIDEO, "sohu video" } },
	{ "124.227.27.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_SOHU, SDPI_APP_CATEGORY_VIDEO, "sohu video" } },
	{ "220.181.90.121",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_VIDEO_SOHU, SDPI_APP_CATEGORY_VIDEO, "sohu video" } },

	////11平台
	{ "124.225.182.168", 32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_GAME_11, SDPI_APP_CATEGORY_GAME, "11 GamePlatform" } },
	{ "119.29.226.34", 	 32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_GAME_11, SDPI_APP_CATEGORY_GAME, "11 GamePlatform" } },
	{ "115.236.23.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_GAME_11, SDPI_APP_CATEGORY_GAME, "11 GamePlatform" } },

	////QQ: sz, sz1-9, tcpconn, tcpconn1-6
	{ "125.39.45.0",     24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "125.39.132.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "111.161.107.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "14.116.136.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "59.36.119.0",     24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "59.36.120.0",     24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "59.60.10.0",      24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "163.177.87.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "163.177.90.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "163.177.93.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "163.177.94.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "220.249.245.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "183.232.127.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "183.232.93.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "183.232.94.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "120.204.17.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "61.151.180.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "101.226.93.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "101.227.152.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "111.30.159.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "111.30.142.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "123.151.77.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "123.151.78.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },
	{ "223.166.151.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "QQ" } },

	//WeChat: login.wx2, wx.qq, wx2.qq, mp.weixin.qq, res.wx.qq
	{ "14.17.43.0",      24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "wechat" } },
	{ "113.96.233.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "wechat" } },
	{ "101.227.160.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "wechat" } },
	{ "101.226.76.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "wechat" } },
	{ "180.163.21.0", 	 24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "wechat" } },
	{ "124.226.64.0", 	 24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_CHAT_QQ, SDPI_APP_CATEGORY_CHAT, "wechat" } },

	//斗鱼直播: www.douyu
	{ "61.145.100.254",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_DOUYU, SDPI_APP_CATEGORY_TVLIVE, "douyu Live" } },
	{ "113.16.210.132",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_DOUYU, SDPI_APP_CATEGORY_TVLIVE, "douyu Live" } },

	////虎牙直播: www.huya, 资源
	{ "180.136.97.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_HUYA, SDPI_APP_CATEGORY_TVLIVE, "huya Live" } },
	{ "222.84.158.203",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_HUYA, SDPI_APP_CATEGORY_TVLIVE, "huya Live" } },
	{ "124.227.184.120", 32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_HUYA, SDPI_APP_CATEGORY_TVLIVE, "huya Live" } },

	//熊猫直播: www.panda.tv， 资源
	{ "14.215.101.123",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_PANDA, SDPI_APP_CATEGORY_TVLIVE, "panda Live" } },
	{ "113.16.210.154",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_PANDA, SDPI_APP_CATEGORY_TVLIVE, "panda Live" } },

	//火猫直播: www.huomao
	{ "113.16.212.188",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_HUOMAO, SDPI_APP_CATEGORY_TVLIVE, "huomao Live" } },
	{ "113.107.57.214",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_LIVE_HUOMAO, SDPI_APP_CATEGORY_TVLIVE, "huomao Live" } },

	//QQ邮箱: mail.qq, tajs.qq, pingtas.qq, ssl.captcha.qq, ssl.ptlogin2.qq, ty.captcha.qq, wp.mail.qq
	{ "14.18.245.237",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_QQ, SDPI_APP_CATEGORY_MAIL, "qq mail" } },
	{ "14.215.138.25",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_QQ, SDPI_APP_CATEGORY_MAIL, "qq mail" } },
	{ "183.3.226.92",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_QQ, SDPI_APP_CATEGORY_MAIL, "qq mail" } },
	{ "183.3.235.28",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_QQ, SDPI_APP_CATEGORY_MAIL, "qq mail" } },
	{ "119.147.83.18",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_QQ, SDPI_APP_CATEGORY_MAIL, "qq mail" } },
	{ "183.3.225.72",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_QQ, SDPI_APP_CATEGORY_MAIL, "qq mail" } },
	{ "59.37.116.35",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_QQ, SDPI_APP_CATEGORY_MAIL, "qq mail" } },
	{ "219.133.60.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_QQ, SDPI_APP_CATEGORY_MAIL, "qq mail" } },

	//网易邮箱: mail.163, mail.126, mail.yeah.net,统一认为是163邮箱
	{ "220.181.12.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_163, SDPI_APP_CATEGORY_MAIL, "wangyi mail" } },
	{ "59.111.160.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_163, SDPI_APP_CATEGORY_MAIL, "wangyi mail" } },
	{ "220.181.72.147",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_163, SDPI_APP_CATEGORY_MAIL, "wangyi mail" } },
	{ "220.181.15.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_163, SDPI_APP_CATEGORY_MAIL, "wangyi mail" } },
	{ "123.58.177.104",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_163, SDPI_APP_CATEGORY_MAIL, "wangyi mail" } },
	{ "222.181.87.132",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_163, SDPI_APP_CATEGORY_MAIL, "wangyi mail" } },

	//GMAIL: 暂时不能访问

	//OUTLOOK邮箱：www.outlook, outlook.live, login.live, outlook.office365
	{ "40.100.56.226",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },
	{ "40.100.57.194",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },
	{ "40.100.57.210",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },
	{ "13.107.42.11",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },
	{ "111.21.29.254",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },
	{ "131.253.61.0",    24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },
	{ "52.98.77.98",     32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },
	{ "52.98.67.162",    32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },
	{ "23.209.177.151",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_MAIL_OUTLOOK, SDPI_APP_CATEGORY_MAIL, "outlook mail" } },

	//购物网站IP更换太频繁，根据host判断更好

	//新浪博客: weibo, img.t.sinajs.cn, js.t.sinajs.cn, ww4.sinaimg.cn, tva3.sinaimg.cn, wx4.sinaimg.cn
	{ "180.149.138.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_WEIBO_SINA, SDPI_APP_CATEGORY_SOCIAL_NETWORK, "sina weibo" } },
	{ "180.149.134.0",   24,{ SDPI_INSPECTED_BY_IP, SDPI_APP_WEIBO_SINA, SDPI_APP_CATEGORY_SOCIAL_NETWORK, "sina weibo" } },
	{ "222.218.87.133",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_WEIBO_SINA, SDPI_APP_CATEGORY_SOCIAL_NETWORK, "sina weibo" } },
	{ "113.16.208.221",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_WEIBO_SINA, SDPI_APP_CATEGORY_SOCIAL_NETWORK, "sina weibo" } },
	{ "58.63.236.212",   32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_WEIBO_SINA, SDPI_APP_CATEGORY_SOCIAL_NETWORK, "sina weibo" } },
	{ "219.151.27.163",  32,{ SDPI_INSPECTED_BY_IP, SDPI_APP_WEIBO_SINA, SDPI_APP_CATEGORY_SOCIAL_NETWORK, "sina weibo" } },
};
#endif